# Generated by Django 3.2.14 on 2022-08-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('date', models.DateField(verbose_name='날짜')),
                ('todo_type', models.TextField(choices=[('PROJ', 'Project'), ('ETC', 'ETC')], max_length=4, verbose_name='todo type')),
                ('is_done', models.BooleanField(default=False, verbose_name='완료여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('date', models.DateField(verbose_name='날짜')),
                ('start_time', models.TimeField(verbose_name='시작시간')),
                ('end_time', models.TimeField(verbose_name='종료시간')),
                ('plan_type', models.TextField(choices=[('IP', 'Ideal Plan'), ('CP', 'Currently Plan')], max_length=2, verbose_name='plan type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
    ]
